name: "Build and upload to PyPI"
on:
  release:
    types: ["published"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.6"

      - name: "Install packaging tools"
        run: "python -m pip install --upgrade build twine"

      - name: "Build dist package"
        run: "python -m build"

      - name: "Upload to PyPI"
        run: "python -m twine upload dist/*"
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: "${{ secrets.PYPI_ACCESS_TOKEN }}"
